"""Update Table Programs

Revision ID: 487f1a3e42fd
Revises: c0b1c7a4d540
Create Date: 2025-08-09 18:20:21.277866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487f1a3e42fd'
down_revision: Union[str, Sequence[str], None] = 'c0b1c7a4d540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('DESIGN', 'PROGRAMMING', 'ROBOTICS', 'DEVELOPMENT', 'COMPUTER_SCIENCE', 'COMPUTERS', name='program_category_enum', ), nullable=False, server_default='информатика'))
        batch_op.create_index(batch_op.f('ix_programs_short_name'), ['short_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_short_name'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
